export const EPICURE = "EPICURE";
export const RESTAURANTS = "Restaurants";
export const CHEFS = "Chefs";
export const HERO_CARD_TEXT = "Epicure works with the top chef restaurants in Tel Aviv";
export const HERO_SEARCH_PLACEHOLDER = "Search for restaurant, cuisine, chef";
export const POPULAR_RESTAURANTS = "POPULAR RESTAURANT IN EPICURE:";
export const ALL_RESTAURANTS = "All Restaurants ";
export const SIGNATURE_DISHES = "SIGNATURE DISH OF:"
export const ICON_MEANING = "THE MEANING OF OUR ICONS:"
export const SPICY = "Spicy";
export const VEGETARIAN = "Vegetarian";
export const VEGAN = "Vegan";