export const EPICURE = "EPICURE";
export const RESTAURANTS = "Restaurants";
export const CHEFS = "Chefs";
export const HERO_CARD_TEXT = "Epicure works with the top chef restaurants in Tel Aviv";
export const SEARCH_PLACEHOLDER = "Search for restaurant, cuisine, chef";
export const POPULAR_RESTAURANTS = "POPULAR RESTAURANT IN EPICURE:";
export const ALL_RESTAURANTS = "All Restaurants ";
export const SIGNATURE_DISHES = "SIGNATURE DISH OF:"
export const ICON_MEANING = "THE MEANING OF OUR ICONS:";
export const SPICY = "Spicy";
export const VEGETARIAN = "Vegetarian";
export const VEGAN = "Vegan";
export const CHEF_OF_WEEK = "CHEF OF THE WEEK:";
export const ABOUT_US = "ABOUT US:"
export const ABOUT_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum non eu ipsum. Cras porta malesuada eros, eget blandit turpis suscipit at. Vestibulum sed massa in magna sodales porta. Vivamus elit urna, dignissim a vestibulum."
export const ABOUT_TEXT_2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum no eu ipsum. Cras porta malesuada eros."
export const CONTECT_US = "Contect Us";
export const TERM_OF_USE = "Terms of Use";
export const PRIVACY_POLICY = "Privacy Policy";
export const BAG_EMPTY = "YOUR BAG IS EMPTY"
export const SEARCH = "Search";
export const RESTAURANT_PAGE_ROUTE = "/restaurants/:id"
export const NO_DISHES = "No dishes available for this meal.";
export const OPEN_NOW = "Open now";